name = "MSTech"
license = "MIT"
licenselink = "https://github.com/themefisher/liva-hugo/blob/master/LICENSE"
description = "Tecnologia, software development & lifestyle"
homepage = "https://mstech.cloud"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'gethugothemes', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.58.0"

[author]
  name = "Manuel Sansone"
  homepage = "https://mstech.cloud"